### ISSUE TITLE
Align to pixels while dragging

### ISSUE THREAD

**Issue by bjorn** [vchelaru/Gum#1]
I've found an option in the project preferences to align the images to pixels, which I find really useful. However, what I find a little annoying is that it only aligns the object to pixels when you release the mouse. It would be more comfortable if it did this while dragging so you get more immediate feedback.

Maybe related to this, the "RestrictToUnitValue" option seems to not be applied when dragging new things into view, where I see fractional positions appear even at 100% zoom. Of course it's a minor issue since you usually move it afterwards anyway.

**Comment by vchelaru** [comment]
Fixed

91803e35e2120809ad2f476ed5ab79db44adb24a
