### ISSUE TITLE
Add documentation about how default variables behave in states

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#10]
If a state explicitly sets a variable then that variable will change in an animation, but it will not interpolate if the other state in an animation does not explicitly set it. This should be called out in a tutorial as it's a pretty critical understanding when making animations.

**Comment by vchelaru** [comment]
Comment by @bjorn :
Hmm, that is really strange, isn't it? I would expect it to animate to whatever the "effective value" of the variable is, whether it is set explicitly or not. This is what my UI system does at least, as well as what Qt Quick does. 

Is there any reason to keep it that way and just document it, rather than changing it to be more what you would expect?

**Comment by vchelaru** [comment]
@bjorn So the idea is that if one of the frames sets a value but the other frame doesn't, then the interpolation would occur between the explicitly set value and the value on the default state?

**Comment by bjorn** [comment]
Exactly.

**Comment by vchelaru** [comment]
This is an old card but I thought I'd wrap it up by linking to the docs about category variable ownership.

https://docs.flatredball.com/gum/intro-tutorials/state-categories
