### ISSUE TITLE
Make framerate configurable (or trigger repaints only when needed)

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#11]
@bjorn  mentioned:

Currently the framerate of the editor is hardcoded on 30. For me this is too low since I want to see a more smooth response while editing. A first solution would be to make the framerate configurable (for example in the project settings, though "user settings" would be more suitable in this case).

Ideally though, the editor would anyway only repaint when necessary. Then, a framerate setting becomes unnecessary since there would be not a general "overhead" introduced by just having the editor open.

**Comment by bjorn** [comment]
Right. I see a timer is used to call invalidate a fixed amount of times (currently 30 by default) per second in `GraphicsDeviceControl`:
```c#
mTimer.Tick += delegate { Invalidate(); };
mTimer.Start();
```
So instead, I guess we could just call `Invalidate()` whenever we actually changed something. Though at the moment I don't know from where such visual changes are made.

**Comment by bjorn** [comment]
Now that #16 is merged I see no reason for a configurable framerate anymore.

Using on-demand invalidation everywhere and getting rid of the timer would probably be quite a change, and does not really have that much benefit. So that'd be something for when we invent a way to stretch time.
