### ISSUE TITLE
"Rotation" property cannot be marked as default or exposed as a variable

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/Gum#110]
My guess is that because Rotation is rendered as a custom control, it doesn't inherit whatever the existing `TextField`s have to deal with setting as variable or resetting values to default.

**Comment by vchelaru** [comment]
Fixed

![image](https://github.com/vchelaru/Gum/assets/729631/eeeb179c-5316-43b7-b0ef-024c7475f928)
