### ISSUE TITLE
Allow dropping into parent

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#12]
@bjorn said:

For initial setup, it would be very nice if you could drop items directly into their parent, rather than setting their parent later via the dropdown.

Of course, visual feedback will need to be given so that the user can pick a suitable drop location.

**Comment by vchelaru** [comment]
The way I've been considering doing this is to allow the user to grab the end of the line that shows the offset of an object and to move it to different parents. This would allow both setting new parents as well as adjusting which corner a child is relative to with the same functionality.

**Comment by bjorn** [comment]
Right, in the same vein, it would be nice if you could click the various origins on the local object to change its origin (adjusting its location accordingly to leave the object in the same place).

**Comment by vchelaru** [comment]
This is implemented in the tree view which works most of the time. I'm going to close this issue since I think the current solution solves the problem.

![2021_May_14_212755](https://user-images.githubusercontent.com/729631/118347272-1e1fe900-b4ff-11eb-8c06-a9fb5ccd2eb5.gif)
