### ISSUE TITLE
Add delete tree view items to right click menu

### ISSUE THREAD

**Issue by KallDrexx** [vchelaru/Gum#131]
Every time I try to delete an element from the tree view, I right click on it and look through the menu.  I am then confused for a second why there's no delete option, and then click off so i can hit the delete key. 

 It's not obvious the delete key is even usable and there should be a more discoverable way to delete tree view items.

**Comment by vchelaru** [comment]
Added delete option on right-clicking instances:

![image](https://github.com/vchelaru/Gum/assets/729631/5e594536-887a-444b-becf-265b9a9f1317)

Also, if multiple are selected, then the right click menu tells you that:

![image](https://github.com/vchelaru/Gum/assets/729631/d0ff1e29-6815-4acd-83c7-54daac7969c7)

fix:
2017ad008926af248f7eb37f24e7b538c1d55642
