### ISSUE TITLE
Sprite `Source` properties list don't respect texture address for states

### ISSUE THREAD

**Issue by KallDrexx** [vchelaru/Gum#132]
1. Create a sprite
2. Set the texture address to `Entire Texture`
3. Create a state category with 1 state
4. Select the created state
5. Change the texture address to `Custom`
---> Observe the Left, Top, Width, and Height properties do not show up in the editor.  This is because the `Source` field is basing itself on the default state's texture address, not the currently selected state.

https://github.com/vchelaru/Gum/assets/139393/f6a2b941-3984-4323-8789-342c8678d1d7

**Comment by vchelaru** [comment]
Fixed: 2da0ef98ed3183b091a54826adb3511a7841890b
![nBhePdPCMm](https://github.com/vchelaru/Gum/assets/729631/68e9866b-d30d-4374-8e94-a28c3ba43222)
