### ISSUE TITLE
UI incorrectly shows element defaults as container values

### ISSUE THREAD

**Issue by KallDrexx** [vchelaru/Gum#133]
1. Create a new component
2. Set the component's height and width to be 0 and *both* relative to container
3. Drag a text element to the container
4. Select the text element
---> Observe the text instance claims to have a height/width of 0 relative to container, but the rendering shows it as expected (100x150 or w/e)

The Gum UI is showing the incorrect values for instance values that are still the default.  Even when you change the values and do "make default", they default to the "true" values but the UI shows them as defaulting to the component's values.  This does not just happen for text instances and is extremely confusing.

https://github.com/vchelaru/Gum/assets/139393/41050c1a-d13c-4573-8f5c-8ad4ca8a2fcd

**Comment by vchelaru** [comment]
939b85b189b4cf61986051955b8e7261c4ec2dd8

![image](https://github.com/vchelaru/Gum/assets/729631/6a89327a-0b6a-4b81-bb4f-8affba0ba877)
