### ISSUE TITLE
Gum not generating properties for component variables

### ISSUE THREAD

**Issue by KallDrexx** [vchelaru/Gum#135]
[GumLayouts.zip](https://github.com/vchelaru/Gum/files/13813742/GumLayouts.zip)

![image](https://github.com/vchelaru/Gum/assets/139393/6322e8ad-7567-46ef-8691-5d38677db091)

Notice that we have an `Initial Value`, `Max Value`, `Min Value` and `Increment` variables added via the `Add Variable` button.  No where in code gen are these exposed, or these defaults I've set applied.

**Comment by vchelaru** [comment]
Fixed

f83d1e38db0bb8807fe271b4140b0519b829075f
