### ISSUE TITLE
Exposing component variables with the same name causes confusion in gum tool

### ISSUE THREAD

**Issue by KallDrexx** [vchelaru/Gum#136]
1. Create a component named `First`
2. Add a `Text` component to `First`
3. Expose the Text property of the `TextInstance` and name it `TextInstanceText`
4. Repeat the process with a `Second` custom component
5. Create a screen
6. Add a container to the screen
7. Add `First` and `Second` into the component on the screen
8. Change `First`'s text variable to "test1"
9. Change `Second`'s text variable to "test2"
10. Click on the screen
---> Observe two `TextInstanceText` variables show with the same value
---> Observe code gen creates duplicate `TextInstanceText` property
---> Observe right clicking on both exposed variables show they point to the same variable
---> Observe if you unexpose one of them, both remain attached to the screen and gusx

**Comment by vchelaru** [comment]
Fixed
