### ISSUE TITLE
Gum Monogame, LayerCameraSettings.Zoom wierd behavior

### ISSUE THREAD

**Issue by rjtwins** [vchelaru/Gum#153]
Reproduction:
 - Add a layer.
 - Move GraphicalUiElement to layer or add to managers with layer argument.
 - Zoom on layer using the layers LayerCameraSettings.Zoom.

Expected: Element is zoomed according to the LayerCameraSettings.Zoom value
Actual:
Elements borders are "zoomed" or there is no zoom at all.

Example Code:

```
            var rectRuntime = new RectangleRuntime();
            rectRuntime.Width = 100;
            rectRuntime.Height = 100;
            rectRuntime.X = 250;
            rectRuntime.Y = 250;
            rectRuntime.Color = Color.Red;
            rectRuntime.AddToManagers(SystemManagers.Default, _layer);
```

![Game1_07ML9zy62R](https://github.com/vchelaru/Gum/assets/18174634/58422929-4825-42ee-90de-e3ad8c786c66)
Where if the zoom is 1 the border is 1 pixel and the zoom is 0.1 the border is much "fatter".
Above zoom 2 the element disappears, presumably because the camera is now below the element.

When moving more "complex" elements into the layer they are not zoomed at all.

Example Code:

```
            _layer = SystemManagers.Default.Renderer.AddLayer();
            var layerCameraSettings = new LayerCameraSettings();
            layerCameraSettings.Zoom = 1;
            _layer.LayerCameraSettings = layerCameraSettings;
            Screen = GlobalStatic.GumProject.Screens.First(x => x.Name == "Research").ToGraphicalUiElement(SystemManagers.Default, true);
            _researchContainer = Screen.GetGraphicalUiElementByName("ResearchContainer");
            _researchContainer.MoveToLayer(_layer);
```

**Comment by vchelaru** [comment]
Fixed

ce1a26ed9ac37dde94925a798e18bf967e4dfd8f
