### ISSUE TITLE
Add binaries to Github releases

### ISSUE THREAD

**Issue by tomcashman** [vchelaru/Gum#158]
The URL https://files.flatredball.com/content/Tools/Gum/Gum.zip is unavailable.

It would be good if releases were tagged on Github with their associated Gum.zip so that teams can use consistent versions.

**Comment by vchelaru** [comment]
I just tried downloading it and it worked for me - perhaps some hiccup?

That's a good idea about the releases. I'll add binaries to github for future releases.

**Comment by tomcashman** [comment]
Seems to be back now. I'll rename issue to Github binaries :)

**Comment by vchelaru** [comment]
Here's the first relesae. Thanks for the suggestion, I'll continue adding them here as we have new releases.

https://github.com/vchelaru/Gum/releases/tag/June_20_2024

**Comment by tomcashman** [comment]
Awesome, thank you :)
