### ISSUE TITLE
Clarification on Percentage of File Width/Height

### ISSUE THREAD

**Issue by tomcashman** [vchelaru/Gum#159]
We have an image that is 7972x5891 and are using Percentage of File Width/Height for it's size. We've set the percentage to 8% in both dimensions, and would expect it to render at around 637x471. However, it renders at 527x354 in Gum (editor is set to 100% zoom).

Does something else factor into the percentage calculation?

**Comment by vchelaru** [comment]
This may actually be a problem with the image being too large. The problem is that gum is built on XNA and I believe XNA has a limitation of 4096 for image dimensions. You can verify this is the case by trying a smaller image equal to or less than 4096 to see if the behaves the way you expect.

**Comment by tomcashman** [comment]
Confirming that this was the issue. Thanks for the quick reply.
