### ISSUE TITLE
Setting Child Base Type As Parent Causes StackOverflowException

### ISSUE THREAD

**Issue by AristurtleDev** [vchelaru/Gum#161]
## Description
In the GUM Tool, if you set the **Base Type** of a child component to that of the parent component, a `StackOverflowException` will occur.

## How to Reproduce
1. Open the GUM Tool.
2. Save Project
3. Add a new Component, call it "TestParent"
4. Add a child component to it call it "TestChild"
5. In the **BaseType** drop-down for the **TestChild** choose the **TestParent** as the base type

Once you do this, the exception will occur

## Suggestions
Filter the Base Type list of a component so that an parent in it's tree is not an option?

**Comment by vchelaru** [comment]
c7b30a61f308a3f436a682820c4aada83ebc2a4e
