### ISSUE TITLE
Plugin errors when first selecting element

### ISSUE THREAD

**Issue by RudyTheDev** [vchelaru/Gum#166]
In an empty project, select any element under "Standard" for the first time, these 2 pop up:

![gum1](https://github.com/vchelaru/Gum/assets/3857299/cb8b9b47-a3fa-4ef4-9058-37ff0d0e9ae3)

![gum2](https://github.com/vchelaru/Gum/assets/3857299/d0f9c09a-1692-4762-b89e-40b599a18b36)

2024.6.20 (zip from https://docs.flatredball.com/gum/setup), Win 10 Enterprise LTSC 21H2

**Comment by vchelaru** [comment]
Thanks for reporting, I'm investigating now...

**Comment by vchelaru** [comment]
Fixed, published hotfix release: https://github.com/vchelaru/Gum/releases/tag/June_21_2024
