### ISSUE TITLE
How to scroll using the ScrollViewer component by dragging the content without the need to use the scroll bar?

### ISSUE THREAD

**Issue by leandrocurioso** [vchelaru/Gum#190]
I'm developling a game that will be available in mobile devices and it's more natural do scroll the content to roll the viewer area. I wonder if it is possible to use the content itself to drag the viewer.

**Comment by vchelaru** [comment]
Implemented here:

https://docs.flatredball.com/gum/monogame/runtime-objects-graphicaluielement-deriving/interactivegue/rolloverbubbling
