### ISSUE TITLE
[GUM] Tips and Help

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#207]
The Interface has many nuances, behaviors, and functionality that is not obvious or common to me (and maybe others?)

Add a HELP or TIPS section in the Help. Or link to the official documentation in the Help.

1. Explain each item in the Project tab, explain how to use them, the purpose, etc.
2. Explain the States tab (I don't understand this)
3. Explain the Variables that exist, how they work, the different purposes
4. Explain the Editor and it's features, shortcuts, tips
5. Explain the Code gen and other tabs

Suggestions so far I'll be talking about in the video below.

TIPS:
 1. Middle mouse wheel will move editor
 2. SHIFT limit movement in 1 axis
 6. White line from top left of selected object shows it's parent
 7. Standard windows shortcuts:
	CTRL+Z Undo
	CTRL+C Copy
	CTRL+V Paste

 8. Colors on variables:
	white means it's set explicitly
	Green means using the default
 9. Change order: Can move objects UP/DOWN the treeview within a container
	by ALT+ARROW-UP or ALT+ARROW-DOWN
 10. Can filter your project objects to find one by name
 11. Right-click to make default variable value
 12. Moving X/Y/Width/Height via scroll bar on label
 13. Changing Rotation via circle

**Comment by vchelaru** [comment]
I think the documentation is the easier to maintain long-term and it's a catch-all, so I'm going to copy the issues in this card here and link to the documentation. I'll also review the documentation to make sure it covers everything:

* Explain each item in the Project tab, explain how to use them, the purpose, etc.
* Explain the States tab (I don't understand this)
* Explain the Variables that exist, how they work, the different purposes
* Explain the Editor and it's features, shortcuts, tips
* Explain the Code gen and other tabs

Suggestions so far I'll be talking about in the video below.

TIPS:

* Middle mouse wheel will move editor

* SHIFT limit movement in 1 axis

* White line from top left of selected object shows it's parent

* Standard windows shortcuts:
* CTRL+Z Undo
* CTRL+C Copy
* CTRL+V Paste

Colors on variables:
* white means it's set explicitly
* Green means using the default

* Change order: Can move objects UP/DOWN the treeview within a container by ALT+ARROW-UP or ALT+ARROW-DOWN

* Can filter your project objects to find one by name

* Right-click to make default variable value

* Moving X/Y/Width/Height via scroll bar on label

* Changing Rotation via circle

**Comment by kaltinril** [comment]
At a minimum, add a link under the Help drop-down, that takes the user directly to the docs page on flatredball.

![image](https://github.com/user-attachments/assets/8c4d0413-5c2e-45c1-9bd9-0c063457eb91)
