### ISSUE TITLE
Combo Box Form Control

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#213]
Could we get a combo box form control for use with Monogame? Combo Box should have a text field for the current item selected and a dropdown button. Dropdown button creates a container that clips children and automatically populates a scrollbar if required. The container is filled with the options for the combo box. Upon selecting an item in the container the text field updates to the new value and the container closes.

Would be nice to have methods for controlling the dropdown options as well as events being fired when options are selected.

**Comment by vchelaru** [comment]
This was fixed by dc7839faa0cbb84bb50a9eb09e2226cb04a90851
