### ISSUE TITLE
Can we get ScreenRuntimes?

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#218]
I would like to be able to specify runtimes for when screens get loaded just like I can specify them for components.

**Comment by vchelaru** [comment]
Screens and Components are treated the same when calling ToGraphicalUiElement. In other words, you can associate screen names with custom runtime types in ElementSaveExtensions. 

```cs
ElementSaveExtensions.RegisterGueInstantiation("StartScreen",
    () => new StartScreenRuntime());
```

Note that the term _element_ is a generic term referring to any Gum type (Screen or Component).

Here's some new docs showing how to create a custom screen runtime:

https://docs.flatredball.com/gum/monogame/custom-runtimes#custom-runtimes-for-screens

I've also updated the Gum loading sample to have a custom runtime for a screen:

6cf85b45ada09f0d3aae578bb0e0e808c584039e
