### ISSUE TITLE
Combobox Listbox should close when clicked outside of

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#221]
EXPECTATION: If the listbox of a combobox is open then clicking outside of the listbox should close it.

REALITY: If the listbox of a combobox is open, clicking outside of the listbox doesn't do anything.

![ComboBoxProblem](https://github.com/user-attachments/assets/828730d0-4efd-42df-9431-b3cabc5bea1f)

**Comment by vchelaru** [comment]
Fixed by 407212b0327ebc3c3d0a45c96c55a07656197acd
