### ISSUE TITLE
Modal Container

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#222]
I would like to be able to create a modal that has a backdrop. No cursor events should go through the backdrop but they should work on the modal. The gif shows an example of the React Dialog component working exactly like I expect the modal container to. Notice how the buttons that have hover states don't get the hover event when the modal is open.

![ReactExample](https://github.com/user-attachments/assets/a17ea9cd-36e6-4358-8f1e-26fedcce83c7)

**Comment by vchelaru** [comment]
This is finished. You can see samples of how it's done here:

https://github.com/vchelaru/Gum/blob/13dc92e7d1fe5b954c6e7f14d3d403c778ec8623/Samples/GumFormsSample/GumFormsSampleCommon/Screens/FrameworkElementExampleScreen.cs#L243
