### ISSUE TITLE
Documentation for using files generated by code gen

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#227]
Can we get documentation for how to use the files generated by gum's code gen?

**Comment by vchelaru** [comment]
First pass:

https://docs.flatredball.com/gum/code-tab

**Comment by vchelaru** [comment]
I'm reviewing this and I've found a few problems:

- [ ] Documentation should explain that you add the directory of your csproj, not the csproj itself
- [ ] Code Project Root should immediately switch to being relative when tabbing out of the text box
- [x] Documentation should suggest adding `using MonoGameGum.GueDeriving;` to the using statements
- [ ] InitializeInstances should not cause compile errors
- [ ] When initializing, the following should not happen: `Cannot dynamically create an instance of type 'IconRuntime'. Reason: No parameterless constructor defined.` This should have 0 or 2 args depending on whether it's a forms or not forms object. 
- [ ] Toggling `IsCodeGenPluginEnabled` should disable automatic generation.
