### ISSUE TITLE
[GUM] CodeGen from Screen doesn't produce drawable code

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#231]
When I create a screen, add things to it, and then click the code gen.  I get a complete set of commands to generate my combined set of standard and components in my screen.

However, when I try to DRAW my screen, it doesn't seem to work.  Under AssignParents I had to change this line of code

`this.WhatThisContains.Add(ContainerInstance);`

To this:
`this.Children.Add(ContainerInstance);`

There may be a more official way to render the screen/combined objects, but it's not well understood or documented if there is.

**Comment by vchelaru** [comment]
Thanks for spotting this - the reason this was happening is because the WhatThisContains is codegen that was written for the Skia runtime of Gum. 

I've updated the codegen to use Children if your Output Library is MonoGame:
9673fa4210cabc2240d5f354fa4812868fee0a0b
