### ISSUE TITLE
Document using .achx + MonoGame Gum

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#235]

**Comment by Fabbbou** [comment]
+1, thanks :)

**Comment by vchelaru** [comment]
To use .achx files:

1. Create an .achx file using the FRB AnimationEditor: https://docs.flatredball.com/flatredball/glue-gluevault-component-pages-animationeditor-plugin
2. Reference the .achx on a Sprite: https://docs.flatredball.com/gum/gum-elements/sprite/source-file
3. Call AnimateSelf on the root GraphicalUiElement: https://docs.flatredball.com/gum/gum-code-reference/graphicaluielement/animateself
