### ISSUE TITLE
Include symbols with nuget packages

### ISSUE THREAD

**Issue by RychuP** [vchelaru/Gum#241]
Symbols greatly improve debugging experience. They map compiled assemblies to source code that was used to build them, they allow to step-through code as it runs in debug mode, they provide more information on a stack trace when the application crashes, etc. I think GUM users will greatly benefit from having the symbols included with the future nuget packages. More information can be found [here](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg).

**Comment by vchelaru** [comment]
This is done
