### ISSUE TITLE
Issue with Scrollviewer that causes children layout to be changed on scroll

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#243]
I created a scrollviewer and added colored rectangles to it. When I scroll on the scroll viewer it changes the child layout from top to bottom stack to left to right stack.

I made a repo that showcases the issue here: https://github.com/legendaryfishtrap/ScrollViewerIssues

Here is a gif showcasing the issue.
https://github.com/user-attachments/assets/6b737e8d-6bc0-4fbb-b4a8-1c63accd8e3c

**Comment by vchelaru** [comment]
This issue was caused by wrapping children. I believe this has been fixed.
