### ISSUE TITLE
World Space UI Elements

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#251]
Is it possible to get more controls with GumBatch so specific UI elements can be rendered in world space while the rest of the system isn't?

**Comment by legendaryfishtrap** [comment]
```
var viewportAdapter = new BoxingViewportAdapter(
   Window,
   GraphicsDevice,
   1920,
   1080
);
var camera = new OrthographicCamera(viewportAdapter);
var cameraMatrix = camera.GetViewMatrix();

GraphicsDevice.SetRenderTarget(cameraTarget);
GraphicsDevice.Clear(Color.Transparent);
spriteBatch.Begin(
    transformMatrix: cameraMatrix,
    blendState: BlendState.AlphaBlend
);
// Draw stuff here
// spriteBatch.Draw()
spriteBatch.End()
```

This is an idea of how I would normally draw stuff in world space using the traditional sprite batch.

**Comment by vchelaru** [comment]
You can now pass a matrix to GumBatch. This is currently on the branch:

https://github.com/vchelaru/Gum/tree/251-world-space-ui-elements

If this is good enough, I can merge it into master. I'll keep the branch open in case any changes are needed.

**Comment by legendaryfishtrap** [comment]
I gave this a try.

I pass in the view matrix but it doesn't change anything about what gets rendered. The rendering is the same on this branch as it is on master.

To get an idea of how I am trying to use this I created a container that is suppose to be positioned around my entity. This container has an X and Y in world coordinates and it's with and height are the same entity in world space. I would expect that if I pass the camera matrix in, a container will be rendered in world space over the entity. Currently it is still rendering in screen space.

**Comment by vchelaru** [comment]
Sorry for that, it was a super rushed job and it turns out I had missed some important things. I made some updates to `251-world-space-ui-elements` and have tested it in a sample project and it works...at least in a basic case. Can you give it another shot to see if it works?
