### ISSUE TITLE
[GUM Tool] Standard element TEXT.Max_Letters_to_Show default value is null not 0

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#255]
If this is the number of letters (Integer) why is it showing the user "null" and not 0?

![image](https://github.com/user-attachments/assets/5b091658-aee9-4050-95f4-9761f3f93ee1)

**Comment by vchelaru** [comment]
0 would mean "max letters are 0" - so no letters would show. 

"<NULL>" means "there is no max" - so all letters show.

To help avoid confusion for other users I have:

1. Updated the property grid to indicate what "<NULL>" means: 
![image](https://github.com/user-attachments/assets/033a6b07-cd18-42db-915e-25cc2655fcda)
1. Updated the docs to include this info in the introduction: https://docs.flatredball.com/gum/gum-elements/text/maxletterstoshow 
![image](https://github.com/user-attachments/assets/29f4f159-6dc7-4a66-863d-1084abb5eda0)

**Comment by kaltinril** [comment]
Thank you for the documentation update.  Still feels weird.  Would prefer seeing "Infinite" or "no limit" being displayed in the box instead of <NULL>

**Comment by vchelaru** [comment]
In this case, the property grid is automatically displaying `<NULL>` because that is the default behavior of the property grid for an `int?` type. Changing what that displays would be possible but it's a bit more work.
