### ISSUE TITLE
[GUM Tool] Absolute Modified by Font scale - Broken?

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#258]
Either I don't understand how it works, or it's broken.

At minimum, I couldn't find any documentation related to it.

I added a container
I added a colored rectangle instance
I added a text instance inside the colored rectangle instance
I changed the text font scale to 2
I changed the colored rectangle instance to Absolute Modified by Font Scale (Width and height)

As I change the font scale, the rectangle does not adjust.

**Comment by vchelaru** [comment]
I have updated the documentation to explain that this is currently not a property that can be tested in the editor. It is based on a global "font scale" which would be assigned in runtime.

https://docs.flatredball.com/gum/gum-elements/general-properties/width-units#absolute-multiplied-by-font-scale
