### ISSUE TITLE
Clarification on Text element Width

### ISSUE THREAD

**Issue by tomcashman** [vchelaru/Gum#260]
I'm looking for clarity on how Text element width is calculated.

In the following hierarchy:
<img width="158" alt="image" src="https://github.com/user-attachments/assets/a45db36b-3ec5-4707-9efd-96f0513c1fe9">

The ContainerInstance width is Absolute set to 1000.
The TextInstance width is set to RelativeToContainer with a value of 0.
The ButtonInfo (another text element) X is set to Percentage Parent Width with a value of 120.

My expectation based on the above is that TextInstance width would be 1000 and the ButtonInfo X would end up with a value of 1200. Is my understanding correct?

In editor, the TextInstance width seems to be based on the content of the Text and "Make Quest Active" is the ButtonInfo.

In the screenshot below, the letter A is the TextInstance content.
<img width="586" alt="image" src="https://github.com/user-attachments/assets/86ee78a4-0a67-496e-894c-df2de8034023">

**Comment by vchelaru** [comment]
From what you've described that is also what I would expect. It sounds like there may be some circular reference or confusing dependency that is making the Text fall back to using its own size. 

Would you be able to upload a project that I could try out to see if I can diagnose the problem?
Also, if you select the items and mouse over the left or right handles, some text should appear giving you info about how the size was calculated.

**Comment by vchelaru** [comment]
On second thought, I'm re-reading what you've written and you said:

> The TextInstance width is set to RelativeToContainer with a value of 0.

TextInstance width would then depend on Button. I don't see where you specified what Button's Width and WidthUnits are set to.

**Comment by vchelaru** [comment]
Yes, whatever is the immediate parent

**Comment by tomcashman** [comment]
Thanks for clarifications 😸

**Comment by vchelaru** [comment]
I understand why this could be confusing - I've updated the documentation for Width Units and Height Units to clarify this point. Thanks!
