### ISSUE TITLE
QOL: Bad undo experience

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#271]
I was trying to undo the changes I accidently did dragging multiple TextInstances to the Screen.

However, I accidently "UNDID" all the other work I had done because I spammed CTRL+Z.  It didn't seem like anything was changing at first.

I didn't realize that the Undo was apparently PER SCREEN or PER ELEMENT?

So when I finally clicked on TItleScreen and spammed CTRL+Z, the entire canvas went blank.  

This would be fine, except, Gum has some sort of "AutoSave" feature with no backup or Redo option.

**Suggestions:**
1. Required: Add REDO (CTRL+Y) or whatever
 
 - Normal behavior is that, once an action is performed after the CTRL+Z, the future CTRL+Y is discarded because you create a new timeline ala (Back To The Future).
 

2. Optional/Alternative: Allow AutoSave to be disabled (Possibly?), sort of only needed if CTRL+Y isn't implemented.

3. Optional: Show a bar of the undos/redos with a snapshot of the changes every N ?

**Comment by vchelaru** [comment]
Lots of work to do here so here's a checklist of improvements:

## Undo Tab

The undo tab currently only tells you how many undos you have. Instead, it should tell you what will happen when you perform the undo:

- [ ] Variable changes in default state
- [ ] Deletion of states
- [ ] Addition of states
- [ ] Changes to variables in a categorized state
- [ ] Addition of variables to a category - undoing this should remove the variable addition from the entire category
- [ ] Removal of variables from a category - undoing this should re-add all variables and also the specific value assigned
- [ ] Addition of new instances
- [ ] Deletion of instances
- [ ] Name change of instance
- [ ] Name change of entire component
- [ ] Name change of state
- [ ] Name change of category

**Comment by kaltinril** [comment]
These items do not reflect under the UNDO History tab:

1. BaseType - It does correctly UNDO and REDO for BaseType change, just doesn't add it to the Undo tab list
2. Locked checkbox (Clicking this doesn't show anything in the Undo Tab history)


Missing Functionality:
1. Moving an element within a tree doesn't add it to the Undo history, and also you can't undo placement change
2. Bring to front doesn't show anything in the history (Which is a side-effect of above)
3. Behavior's do not reflect their Category/State changes in the Undo History, nor does the UNDO or REDO work.
4. Creating a new Component does not show up in any Undo History

Broken Functionality:
1. Adding a behavior to a component shows up in undo history
2. Removing a behavior from a component does not add the remove delete to the history

Bug/Error/Crash:

1. I attempted to delete a Category which included a state and got these errors
![image](https://github.com/user-attachments/assets/d2b3397e-7956-4e25-8a5a-d7df847adbe1)
![image](https://github.com/user-attachments/assets/ffd69bb0-47d8-46c5-8534-296ceff26fbf)

**Comment by kaltinril** [comment]
Also:
1. Undoing collapses the treeview of the items

![1FpMDe17nI](https://github.com/user-attachments/assets/0d56b4e6-95d9-494e-9744-016806e73779)

**Comment by kaltinril** [comment]
Bug with Polygon and undo

Steps to reproduce:
1. Click to add 4 nodes
2. Drag the BOTTOM one up
3. Drag the TOP one down
4. Undo until you get the error.

![image](https://github.com/user-attachments/assets/d7933a6f-337d-4411-8ea6-e64c579c1c5d)

**Comment by vchelaru** [comment]
Thanks for all the feedback and testing! All issues are resolved here with the exception of adding "project wide" undos. Currently each element has its own undos, so for the sake of separating out tasks so we can get them out in a release, I'm going to only focus on undos within a particular component. This means that the following issues are not yet being fixed:

* Creating a new Component does not show up in any Undo History
* Project Properties are missing from undo history

I'm going to close this issue out because I believe the new undo system is working fairly well and we've done a bit of testing. Any additional bugs that we find can be added as separate issues.
