### ISSUE TITLE
Expected behaviour of Percentage 0%

### ISSUE THREAD

**Issue by tomcashman** [vchelaru/Gum#281]
One of our designers set up the following hierarchy.
<img width="188" alt="image" src="https://github.com/user-attachments/assets/2f666c11-475e-4d0e-9577-61b4435f5d85">

For the following component.
<img width="280" alt="image" src="https://github.com/user-attachments/assets/b1f60bc5-8932-4f3f-b695-178d9eb839fa">

"Button" is a Sprite that is set to 100% percentage of file width (the bg of the X icon)

ButtonInfo is a Text element (View on Map in the image) that has its width/height set to zero Percentage of Container.

In this case, I would expect the Text element to not display but it seems like zero percent is treated as a special case?

**Comment by vchelaru** [comment]
Yes this may actually be a special case from long ago. I know it's a breaking change, but I do believe that 0% should be treated as 0 width. so I'll likely change that in the next version. Is this something you need fixed asap?

**Comment by tomcashman** [comment]
Thanks for the clarification. Not urgent on our end :)

**Comment by vchelaru** [comment]
This has been fixed in source and it will be available in the next release.
