### ISSUE TITLE
BUG: Wrong Object updated - Wrong State/Variables tabs displayed

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#282]
Steps to reproduce behavior

1. Click on an Instance
2. Click and drag a Behavior to the States (I was trying to figure out how to add behavior, don't ask)
3. Obviously step 2 doesn't DO anything, however, now the Behavior you clicked on is selected, but notice that the States and Variables still reflect the INSTANCE.  Now right-click and add a category to the states and notice it is added instead to the BEHAVIOR instead of the INSTANCE because the CLICK+DRAG selected the behavior, but never updated the tab's contents.

![dHEf0eXt2z](https://github.com/user-attachments/assets/592baddc-1509-412e-9ba8-4ec5eb27a0a6)

**Comment by vchelaru** [comment]
Fixed by 3e123616856be6717c66b49b4f5dfcd5f9136907
