### ISSUE TITLE
BUG: Error when check-marking Ignored by Parent Size

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#284]
Steps to reproduce

1. Load up a project
2. Click on a standard control
3. Check-mark the `Ignored by Parent Size` property
4. Error appears

![C5Vfl2xsKl](https://github.com/user-attachments/assets/b35de414-68e2-4c5d-887c-28f08d0625ae)

**Comment by vchelaru** [comment]
Note: this only reproduces if codegen for MonoGame is enabled.
