### ISSUE TITLE
BUG: (Small) During and AFTER a drag of a polygon the codegen doesn't update

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#292]
Steps to reproduce:
1. Add a polygon
2. Drag points around with codegen enabled
3. Notice the points do not update
4. Now do something to force the refresh (Change the Inheritance Location, or drag the entire object)
5. Now it shows the correct points

![MkR1WfoGY0](https://github.com/user-attachments/assets/6fe7b95a-4275-4405-84c1-f7bfc2804776)

**Comment by vchelaru** [comment]
Fixed by c2b1dbfd3d68b7973ef8726a983ca78cbdff89a9
