### ISSUE TITLE
Gum w/Glue: Cannot add a gum screen as an object.

### ISSUE THREAD

**Issue by alexnaraghi** [vchelaru/Gum#30]
1) Add a gum scene file to a screen.
2) Create new object -> From File -> GumProject/Screens/TestScreen.gusx -> Source Name = "Entire File (GameplayRuntime)"
3) Execute application.
4) Error is thrown: Error	141	Cannot implicitly convert type 'FlatRedBall.Gum.GumIdb' to 'GameProject.GumRuntimes.GameplayRuntime'	...\Screens\TestScreen.Generated.cs
5) If on step 2, Source Name is changed to "Entire File (GumIdb)", the app seems to generate the same instance variable of type FlatRedBall.Gum.GumIdb.  Maybe code is partially being generated for the wrong source file option?

**Comment by bjorn** [comment]
Superceded by #31.

Please edit issues rather than opening new ones. :-)
