### ISSUE TITLE
BUG: Should be able to expose Text Horizontal Alignment and Vertical Alignment by clicking on the label

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#301]
I was going to make a shared font to use in the demo of the Kenney UI but I couldn't expose the Alignment values.

![image](https://github.com/user-attachments/assets/b076e13f-a231-40ac-90e0-6d4c19e807a8)

**Comment by kaltinril** [comment]
EDIT: It appears you can, but you have to click on the ICONS and not on the LABEL.

SO I guess its a bug, make it so right-clicking the label also allows exposing the variables.

**Comment by vchelaru** [comment]
![06_06 33 50](https://github.com/user-attachments/assets/2ac73f8c-3306-4efb-9776-b5a5cbe1c583)
