### ISSUE TITLE
BUG: Gum.Forms.Monogame (CodeGen) - IconRuntime [SpriteRuntime]

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#310]
At least 5 issues.  It seems that generating the `SpriteRuntime.Generated.cs` overrides the `MonoGameGum.GueDeriving.SpriteRuntime`.  This ends up breaking many things it looks like?  Maybe I'm just doing it wrong?  Unsure, not clear.

1. "The type name 'ColorCategory' does not exist in the type 'SpriteRuntime"

SpriteRuntime comes from MonoGameGum.GueDeriving by default.

However, apparently a user needs to CodeGen the Standard Sprite object.  This is not obvious because the error hides this.

![image](https://github.com/user-attachments/assets/a19938f4-6226-4506-9a03-b5cf1620201c)

2. "The property or indexer 'SPriteRuntime.ColorCategoryState' cannot be used in this context because it lacks the get accessor".

Similar to the IconRuntime, the `SpriteRuntime.Generated.cs` is missing the GET accessor on the `ColorCatgegoryState` property

![image](https://github.com/user-attachments/assets/e6c90b2f-a154-426e-b577-2515a69bcc66)

3. "The name 'Categories' does not exist in the current context".

Some sort of dictionary is missing from the Generated file.

![image](https://github.com/user-attachments/assets/cca50d46-c27b-4eb5-94a3-738668d1c1bf)

4. 'SpriteRuntime' does not contain a definition for 'Tag' and no acces........
![image](https://github.com/user-attachments/assets/23bbb3d2-0b51-448d-876f-e7d18f6a861c)

5. 'SpriteRuntime' does not contain a definition for 'ApplyState' and no acces........
![image](https://github.com/user-attachments/assets/bc30e70d-9799-4520-b886-f5905e72741f)

**Comment by vchelaru** [comment]
This should be fixed now by Gum no longer allowing you to generate any StandardElement runtime class.
