### ISSUE TITLE
UNDO/REDO pops out of the selected STATE

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#323]
**Working:** State history is stored and I am able to UNDO and REDO it.

**Not working:**
However, the state treeview is RESET and the View changes back to (almost) the default state view, but sometimes the displayed Editor is odd.

**When Undoing, perform either of these instead of the current behavior:**
A) Jump to the State that is being "undone" ?
B) Stay on the state selected

https://github.com/user-attachments/assets/fce608a0-343f-4079-9da2-780d4a656109

**Comment by kaltinril** [comment]
Still an issue on the new STATE treeview with folder icon.

At a minimum, (Option B) the state selected should not change and the treeviews should not collapse on an undo/redo.

The exception would be if you wish to use option A)
or, if the state you're on disappears because of an undo or redo action.

**Comment by vchelaru** [comment]
Fixed by 46fdf81adbd82ad431d22a187cdad2451a8a47bd
