### ISSUE TITLE
Review invalid/unusable options and document, disable, or provide information in Gum

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#327]
From @kaltinril

> I feel like there are many buttons, drop downs, options, and variables that don't do anything in gum, unless a specific set of criteria is in place first.
> Yet these things are still clickable, changeable, and set-able.
> Examples:
> Wrap (doesn't work for all texture address options)
> Text word cutoff (only works if like wrapping is? disabled? )
> There are others, these are just the two off the top of my head.
> 
> Story mode:
> I have 2 light switches in my house that I still, to this day, have no idea what they do.  I still flip them on occasion hoping they'll do something.
> 
> Question:
> Why not disable, Grey out, or hide these options until they are available functionally to the user?

**Comment by kaltinril** [comment]
I'm going to compile a list and NUMBER them like with the tutorial, I'll keep editing this, when I'm done I'll update this to say [done] at the top

1. State's right-click, when at the bottom of a category, do not display the move down option.  When at the top do not display the move up option.
![image](https://github.com/user-attachments/assets/a4d4f4ba-7449-4236-b8d6-5a31ede6ff19)

2. Standard Instance on a Component, Locked button, doesn't do anything.  Why is it here?


3. Sprite - Wrap - Entire Texture (No wrapping or tiling occurs, so why is this option click-able?)
![Gum_VN8YGM9kjM](https://github.com/user-attachments/assets/3c3231a7-ae9c-4a56-a482-68677600e596)


4. State Drop down - Null or Default.  Why?  If I don't have any categories or states why would this exist as a drop down?

![image](https://github.com/user-attachments/assets/cfce219b-b2d7-4c80-b333-c868113490a9)

**Comment by kaltinril** [comment]
**Items Resolved in other tickets**
1. Code was updated and now only the appropriate move up/down option is shown
4/5. Code was updated and no longer shows an empty State drop down
12. This now shows 1 menu item that renames itself from show to hide.

**Items documented, or explained because of other tickets**
2. This locked currently only makes it so that you can't SELECT the element from the EDITOR / Graphical View on the right.  

**Remaining:**
2, 3, 6, 7, 8, 9, 10, 11, 13

**Comment by vchelaru** [comment]
- [ ] 3 - Wrapping checkbox does nothing - this has been resolved with the latest commit
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10
- [ ] 11
- [ ] 13

**Comment by kaltinril** [comment]
I mean, for 8, you could hide it if there are no other screens AND the value is not SET to a screen, that would be a simple null check no?  

Though, the VS way is to show every possible option and just show null/empty/0 so I guess it depends on how you want it to be.

**Comment by kaltinril** [comment]
9 is a little weird.

If the "show codgen preview" is enabled, it disappears
if the "show codegen preview" is disabled, it shows the code window

Why not just hide the entire tab on standard controls?  or is there a purpose for it I"m not understanding?

**Comment by kaltinril** [comment]
confirmed 10

**Comment by vchelaru** [comment]
Update - good call, I've removed the base type (item 8) here;

8ee5ad3fd8b44c8908413e7f595da18af8a1f91a

**Comment by vchelaru** [comment]
Update - ya, I like the idea of keeping the UI simpler if possible, so for now the Code tab is removed completely when no element is selected, or if the element is Standard.

4ce97b11cda3097817df405048f1735518274671
