### ISSUE TITLE
BUG: Polygon - Points list does not update while adding points

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#329]
Steps to reproduce:
1. Add a polygon to the screen
2. Add a new point
3. Scroll through the list
4. Notice it only contains the original 4
5. Move the polygon, points update
6. Click off and back onto the polygon, points update

https://github.com/user-attachments/assets/eb1e9157-7ff6-4ed5-be5b-91daffa0d9f4

**Comment by kaltinril** [comment]
I tried to figure this one out also, but again....., the way the code/logic is so disjointed it's hard to find how anything is wired up and connected.  I do not understand where the update to the Variables tab is happening for the Points, and WHEN.

**My Observations:**
1. Dragging the entire Polygon around will update the Points Listview in the Variables.

2. NOTE: The moment you click the polygon (Not the points) nothing happens, but.... When you start dragging the Polygon, the Points listview in the Variables will update the list of points.  This is BEFORE you left go of the DragNDrop of the entire polygon.

3. Clicking on another Element, and back onto the Polygon DOES update the Points ListView in the Variables.

(Adding a new point)
4. Adding a new point **DOESN'T** update the Points listview in the Variables
5. Adding a new point DOES update the .gucx file's VariableList
6. Adding a new point DOES update the Undo History tab
7. Adding a new point DOES update the CodeGen output

8. For some reason Polygon's have an extra point in the VariableList, the first point is duplicated as the last point ?

(Moving a point)
9. Moving a point **DOESN'T** update the Points listview in the Variables
10. Moving a point DOES update the .gucx file's VariableList
11. Moving a point DOES update the Undo History tab
12. Moving a point DOES update the CodeGen output

13. I was able to find the code where the File save and Undo are stored (WireframeEditor.DoEndOfSettingValuesLogic).  It also contains logic for looping over the VariableLists to see if there were changes.  I stepped through this and it does fire the PluginManager.Self.VariableSet.  I would have thought this is where it was broken.

14. Using the + symbol to try to add a point to the list of points doesn't do anything (This is an unrelated bug I think?)

**Comment by vchelaru** [comment]
Polygon grid now updates when edits are made in the Editor tab

21685e7acf904063cb5c0d27372fe11786b29283

I'm investigating the +

**Comment by kaltinril** [comment]
Why does a polygon have an extra point in the xml that appears to be a duplicate point of the first point?

![image](https://github.com/user-attachments/assets/5c863e5b-a59d-4230-b69b-3f9861bc8514)

**Comment by kaltinril** [comment]
> Polygon grid now updates when edits are made in the Editor tab
> 
> [21685e7](https://github.com/vchelaru/Gum/commit/21685e7acf904063cb5c0d27372fe11786b29283)
> 
> I'm investigating the +

 I validated the fix, it does now correctly update the Points ListVIew, nice work.  So the fix was basically just adding this to a few places?

```csharp
GumCommands.Self.GuiCommands.RefreshVariableValues();
```

**Comment by vchelaru** [comment]
Polygons do not auto close. If you want it to be closed, the last point must be repeated.

**Comment by vchelaru** [comment]
I've made the fix to the + button not working here:

e552824e94d00ea207c0d97a023b9bb4df89c21e

I do feel like working with the list in the variables is not as useful as working with values in the editor. The main reason is that you cannot currently edit points that you've added in the Variables list. If you believe this should be supported, we should make a new task. As is strictly defined, this card is done so I'd like to close out the issue.

Feel free to review it and create additional cards if you think is necessary.

![image](https://github.com/user-attachments/assets/185eae66-254e-4ff9-b481-3e797f7c1634)

**Comment by kaltinril** [comment]
Sounds good.

The only reason for the ticket is to point out missing, incorrect, or broken functionality.

I don't see the points list being very helpful either. If someone really wants to manually edit the points they can use the xml file or code. (opinion)
