### ISSUE TITLE
BUG: State selection "panel" missing title/heading

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#330]
No name for the State selection panel.  

Suggestions:

A) State and Visibility
B) Misc
C) Junk Drawer (joke)

![image](https://github.com/user-attachments/assets/50860092-16b3-4434-a42f-afb8f2131a19)

**Comment by kaltinril** [comment]
I figured most of this out.

If you want to direct me I can finish it.

It's basically just the Category string on the Variables.Add() in the StandardElementsManager class.

However, I got it to MOSTLY work, components won't move the State and I don't understand why.  It seemed to me that Components used the same Method "AddStateVariable" that the rest of the Standard Elements used.  So I do not understand why they don't move to the "States and Visibility" panel?

Also, I fixed my typo in the video below to correctly name it "Visibility" and not "Visability".


https://github.com/user-attachments/assets/5b5ad471-a3f2-4708-bd68-1d31db319821

**Comment by kaltinril** [comment]
I also put a Category on Radius of "Dimensions" since it felt like it belonged in there.
I also moved the "SourceFile" entry from the catch-all empty Category, into the "Source" category as it seemed to belong there.

**Comment by kaltinril** [comment]
I can't figure out how these dynamic categories are added?

![image](https://github.com/user-attachments/assets/9f1b3b48-0d4c-4229-95df-19719569164a)

**Comment by vchelaru** [comment]
See latest push on this branch. If you feel happy with this PR let me know and I can merge it.

**Comment by vchelaru** [comment]
Note that you can mark a PR as a draft so you don't have to put "do not merge" in the title 
![image](https://github.com/user-attachments/assets/a36a36ae-1c38-4e71-a1e8-9a79918426c5)

**Comment by kaltinril** [comment]
> Note that you can mark a PR as a draft so you don't have to put "do not merge" in the title ![image](https://private-user-images.githubusercontent.com/729631/395880459-a36a36ae-1c38-4e71-a1e8-9a79918426c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTI2ODEsIm5iZiI6MTczNDMxMjM4MSwicGF0aCI6Ii83Mjk2MzEvMzk1ODgwNDU5LWEzNmEzNmFlLTFjMzgtNGU3MS1hMWU4LTlhNzk5MTg0MjZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjJkNGJjM2UxMmQ0M2JjMGE0NDhhOGNiNmRlNWRkNTc4NmNmNGEzMGI3NjFlMWExOWQ1OTFlZWUyN2EwMmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WUooY5MRph9emkonUk7nNnsxi20wfV3LsV_AEmHyMNg)

Nice, I did not know that, thank you

**Comment by kaltinril** [comment]
> See latest push on this branch. If you feel happy with this PR let me know and I can merge it.

I've downloaded the change you made and it looks good.  Please approve/merge the PR and close this ticket.
