### ISSUE TITLE
BUG: Behaviors - Adding instances

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#331]
I was playing around with behaviors and dragged a component onto the Behavior and it let me

There were no variables

I then tried to Right-click and got this error, I the tried to delete the instance, and got the error again.

![image](https://github.com/user-attachments/assets/926dad69-bf35-4317-8729-f3f082ee5050)

**Comment by vchelaru** [comment]
Fixed by f221d150e633fd877d11e66f1af046b602c84cb8
