### ISSUE TITLE
Enhancement: Hide Animation tab

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#333]
After I clicked View Animation, there was no way to close that tab.

Steps to reproduce:
1. click State Animation
2. Click View Animiation
3. Tab appears
4. No way to close tab.

![image](https://github.com/user-attachments/assets/6a622d8d-d9ef-4d40-9b9c-d412028743b7)

**Comment by kaltinril** [comment]
If the changes to hiding Hotkey tab are eventually merged in, whatever we do there, I can do the same thing to this tab.  I will wait for feedback on the way I did it on the other PR/Ticket first before duplicating that work here.

**Comment by vchelaru** [comment]
Thanks I'll assign this to you, you should be able to follow how the other tab was done. Note that I added middle-mouse-click support for that other tab, we probably want that here too.

**Comment by kaltinril** [comment]
> Thanks I'll assign this to you, you should be able to follow how the other tab was done. Note that I added middle-mouse-click support for that other tab, we probably want that here too.

I've submitted a PR to add this feature.
