### ISSUE TITLE
Enhancement: Reorder tabs

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#336]
Tabs should be able to be ordered however the user wants, and they should be saved/retained in that order upon restart.

Tabs should be able to be moved between sections (Left, Middle, Right top, Right bottom) at will.

This was a random thought, might not be worth implementing.

**Comment by vchelaru** [comment]
This one is probably quite a bit of work and even though it's nice to have, I vote this is fairly low priority compared to all the other bugs and features we have. 

If @profexorgeek disagreed we can make this higher priority. Thoughts?

**Comment by vchelaru** [comment]
Will not fix this for now, high effort given the benefit.
