### ISSUE TITLE
BUG: Polygon - Adding a point with the Plus Symbol doesn't do anything

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#343]
When I click the Plus symbol, I am assuming the currently intended behavior would be that it's supposed to add a point to the list and the polygon in the editor.

However, right now when I type a point in, it doesn't add anything to the list, and nothing shows up in the editor as a new point.

This functionality and the entire Polygon are not documented so I don't know what this button is "supposed" to do.

**Steps to reproduce:**
1. Add a polygon to a component or screen
2. Click the + (Plus symbol) below the Points ListView.
3. Enter a point.  I tried 10, 10 and <10, 10> and 10,10 (no space), and (10,10)
4. No point appears in the Points Listview, no point appears in the Editor.  No Change to history tab.  No change to Codegen tab.

https://github.com/user-attachments/assets/5286659e-9406-4b49-a176-5c777030ad9e

**Comment by vchelaru** [comment]
Fixed by e552824e94d00ea207c0d97a023b9bb4df89c21e
