### ISSUE TITLE
DOC: Polygon - No documentation exists except a blurb under the Tutorial The Basics

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#344]
I was unable to find any documentation related to the polygon, points, adding points, removing points, etc.

1. Add polygon basic "Gum Elements" page
2. Add details to the new page about the Points listview
3. Explain the polygon, it's purpose, etc.
4. Explain if there are any bad things (Can it be rendered and drawn in monogame?)
5. Add details about the + plus symbol button below the list, what is the purpose, and how do you use it?
6. Explain how to add, remove, and move points.

**Comment by vchelaru** [comment]
Just added:
https://docs.flatredball.com/gum/gum-elements/polygon/points

**Comment by kaltinril** [comment]
Looks good, thank you
