### ISSUE TITLE
BUG: (High) Don't let users see the Add Forms Components after they've used it

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#346]
We should grey out the "Add Forms Components" or remove it once the user has added components.

Why?  I wanted the demo screen but already added components, so I clicked add again, it gave me a giant error but that was after clicking the drop down menu, checking the box, and clicking OK.

This is low priority, because it doesn't cause any issues, and most users are not going to click it twice.

**Steps to reproduce:**
1. In a freshly created/saved gum project
2. Click Content > Add Forms Components...
3. Do not select the checkbox, and click Ok
4. Wait until  the forms components are added
5. Click Content > Add Forms Components...
6. Check the checkbox (or don't) and click Ok
7. Error/Warning appears
8. User should not be able to get this far, don't let them drive down a dark alley, stop them before they go down it.

![image](https://github.com/user-attachments/assets/bcbc75a8-09f4-47bd-9f28-c019345bcf97)

https://github.com/user-attachments/assets/62787f17-b326-42bd-b493-239877bdb954

**Comment by kaltinril** [comment]
@vchelaru  This is broken worse, the option is completely missing now if you don't use it during your initial project creation/save.

Steps to reproduce:
1. Create a project and Save it
2. Notice you have the option to add forms components
3. Close gum
4. Re-open gum
5. Notice that the "Add Forms Components" is missing, but we never used it.


https://github.com/user-attachments/assets/7303e9ca-6d75-47ec-a4e7-08c1d95f8724

**Comment by kaltinril** [comment]
I've changed this to (high) since it makes it so someone won't be able to add forms unless it's a brand new project.

**Comment by vchelaru** [comment]
Another attempted fix 6db7c4e3525eaeabf7b6a2e1aefc3caad3b9f2d0

**Comment by kaltinril** [comment]
This appears to be fixed now
