### ISSUE TITLE
BUG: (Low) Behavior State window should show the Correct options for the behavior selected

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#348]
Currently if you are in a Component's state window and you right-click to show the context menu then you go to a behavior and right-click in the state window of the behavior, it shows you the Components right-click menu instead.

This is low priority because it requires a special set of steps to happen.  The key being that you came to the Behaviors state menu directly after right-clicking the Components State window

Steps to reproduce:
1. Create a component
2. Add a category
3. Add a state
4. Right-click the state
5. Create a behavior
6. Right-click in the state window, and notice it shows the right-click window from the Component (Or a blank right-click menu).  

NOTE: The blank menu only appears if it's a fresh start up of GUM, and you haven't fixed it via right-clicking on the OLD tab first.

Showing the EMPTY right-click menu (Until I go to the OLD state tab)
https://github.com/user-attachments/assets/988019da-ebad-4c7e-ad3c-77dd4001e889

Showing the INCORRECT right-click menu on a behavior (Old or new state tab)
https://github.com/user-attachments/assets/3062cdbb-c149-4e32-979e-01fbf16230e6

**Comment by kaltinril** [comment]
This is 99% fixed.  As long as I click on a STATE or CATEGORY in the behavior first.

If a user right-clicks before selecting a state or category on the Behavior it shows the OLD right-click menu.


https://github.com/user-attachments/assets/a733ca00-fcf5-40ec-b429-4c6890ceed6e

**Comment by vchelaru** [comment]
I believe the latest versions fix this

**Comment by kaltinril** [comment]
This appears to be fixed
