### ISSUE TITLE
GumPlugin cannot be installed and loaded correctly

### ISSUE THREAD

**Issue by Oberon-Zheng** [vchelaru/Gum#35]
Once I installed the gumplugin and restart Glue, it told me : 
8:39:13 - Error trying to load plugins from directory:     C:\Users\36011\AppData\Roaming\FRBDK\Plugins\gumplugin/
System.MissingMethodException: Cannot find method:“Void RenderingLibrary.IPositionedSizedObject.SetParentDirect(RenderingLibrary.IPositionedSizedObject)”
Therefore I found the plugin not installed correctly. I can't use it .

**Comment by vchelaru** [comment]
I am going to release an updated Glue and Gum plugin - this should solve everything. 

Which version of Glue and Gum Plugin are you using?

**Comment by Oberon-Tonya** [comment]
Janurary 5,2016

**Comment by vchelaru** [comment]
@Oberon-Tonya Okay, this should be solved. You need to update to the latest version of Glue and also grab the newest Gum plugin (2 separate things to update).

You can update Glue by running the FRB installer or through Glue's Update FRBDK option.

You can update Gum by downloading and installing the latest plugin:
