### ISSUE TITLE
BUG: Behavior - Sub-instances - Right-click menu - Create Component - Should do something

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#356]
I'm not sure what the option "Create Component" should do.  But I know it should not do nothing.

Currently if you right-click and chose "Create Component", nothing happens.

**Steps to reproduce:**
1. Create a behavior
2. Add a Standard Instance (Text, NineSlice, whatever)
3. Right-click the instance and chose "Create Component"
4. Notice that nothing happens.

**Fix:**
- Either remove the "Create Component" option if it is not supposed to be there.
- or, Fix it so it does whatever it's supposed to do, unsure...

https://github.com/user-attachments/assets/da7145f1-3910-43e4-8589-5e4e83ae283f

**Comment by vchelaru** [comment]
This option should not be available. I removed it here:

1060fb1578d9f54294919e242447ddf12949083a
