### ISSUE TITLE
BUG: (Low Priority) States and Categories - Move To Category - Right-Click menu doesn't refresh after move

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#358]
This is a ridiculously small issue that No one will ever run into.

Super low priority (I am going to see if I can fix this)

Steps to reproduce:
1. Create a component or behavior
2. Create 2 categories (Cat1 and Cat2)
3. Create 1 state in the first category (State1)
4. Right-click the state, and chose "Move to Category" > Cat2
5. Do not click or do anything else!!!!!
6. Right-click the state again, now that it's in Cat2, and chose "Move to Category"
7. Notice that it still shows Cat2 as the only move to option.  
8. It SHOULD show Cat1.

This is because it did not refresh after moving the state to another category.

https://github.com/user-attachments/assets/7b42cf1a-b1eb-401a-8591-4b04e4b63722

**Comment by kaltinril** [comment]
Actually, I don't know how to fix this.  I was going to add a call to PopulateMenuStrip(); but then I realized that MoveToCategory is static, so I have no "this" instance to be able to call PopulateMenuStrip against....

**Comment by vchelaru** [comment]
Fixed in c7453cb3f9fe44d0d2d0e3809d7534a369bbcfd7

**Comment by kaltinril** [comment]
This appears to be fixed, opened a new bug for functionality related to yellow highlighting
