### ISSUE TITLE
BUG: (Low) Polygon - Should not be able to delete all the points if deleting from the Points List

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#361]
Currently if you click on a point and press delete, you can delete all but that last 3 points (4 technically, but the last is a repeat of the first).

However, the Points ListView lets you delete as many points as you want.

The ListView should behave the same way the Editor does and limit your deletions to not delete all the points.

**Steps to reproduce:**
1. Drag a polygon to a component or screen
2. Click in the Points ListView
3. Press delete
4. Click and delete again and again until no points remain
5. Now you can no longer use the EDITOR to add points as there are no line segments.

**Fix:**
Prevent the user from deleting the last 3 points.

This is **low priority**, a user can just UNDO or ADD a fresh polygon.

https://github.com/user-attachments/assets/70625304-0a79-49d4-abd5-653a671bc1ed

**Comment by vchelaru** [comment]
Fixed by c5d76ca4de84b0c97c045d744e8388fc785505e4
