### ISSUE TITLE
HasEvents always loading as true

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#366]
Working with monogame gum forms. I created a custom listBoxItem which children. When trying to interact with the list box items I see that interact events happen. The children of the listBoxItems are consuming the events. I toggle off HasEvent in Gum on all of the children and retry. The children are still consuming the events. If I set the children.HasEvents to false in the code, the children are no longer consuming the events and the list box item works as intended. It seems like HasEvents from Gum isn't being properly loaded in when creating runtimes based on gum files.

**Comment by vchelaru** [comment]
Fixed by f9d1c7a921d27dd56694b888831abe249766eac7
