### ISSUE TITLE
What does the "View Code" option do under Plugins menu?

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#367]
![image](https://github.com/user-attachments/assets/fb523554-9e89-4dd2-a754-2428ab0e067e)

**Comment by vchelaru** [comment]
This is a leftover when the codegen plugin was still experimental and didn't automatically show up. Now it is automatically shown so this can go away.

**Comment by vchelaru** [comment]
07702bb4fd91e4b00bdbb43af1b53012e317b2f6
