### ISSUE TITLE
What is the point of this "Default" state

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#370]
I don't understand.

![image](https://github.com/user-attachments/assets/3075cf89-6d18-45a0-be1d-dfacc92cdbdf)

**Comment by vchelaru** [comment]
It should not show up. Fixing...

**Comment by vchelaru** [comment]
cd1aa8c622a8f003e74348466e8390cc18f46db4

**Comment by kaltinril** [comment]
Validated the Default "State" is gone
