### ISSUE TITLE
BUG: Dragging an instance under a Behavior to a component or screen should not cause an error

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#371]
I was clicking and dragging around testing and I dragged an Instance of a Standard Element that was attached to a behavior onto a Component and the program crashed/had an error.  Same with dragging it onto screen.

I don't know what the purpose of having an instance on a behavior is.
And I don't know if you are supposed to be able to drag it somewhere else
But... it shouldn't cause a crash/error.

Steps to reproduce:
1. create a screen
2. create a component
3. create a behavior
4. drop a standard instance onto the behavior
5. drag the instance under the behavior over to the component or screen
6. error/crash

https://github.com/user-attachments/assets/cbccc12a-a14a-4bd9-8c72-7006111d820e

**Comment by vchelaru** [comment]
fixed 

3b9b8f816d9d692f85c54e0da82265f8208ccd72

**Comment by kaltinril** [comment]
This is fixed, EXCEPT, if you try to drag it to a Standard Element.  Then it gets an error

![image](https://github.com/user-attachments/assets/fc011d71-7663-4516-9e8e-035a88e1043e)

**Comment by vchelaru** [comment]
Fixed b7f69ef67215697c50dc9713d615747e7f77defa
