### ISSUE TITLE
BUG: State yellow highlighting is broken

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#372]
When I click on an instance, it does not highlight the states that that instance has modifications for.

New version
https://github.com/user-attachments/assets/40fb0b54-af3d-4a7d-aab1-b48504223ed8

Old Version
https://github.com/user-attachments/assets/1f2d9b28-8f95-4fcf-81bb-142bbf41c4ac

**Comment by vchelaru** [comment]
Fixed by bfdd5cde6444ccfd52c82ebfa84dc6e6904dfcbc

**Comment by kaltinril** [comment]
Validated that this is working now
