### ISSUE TITLE
BUG: (High) Behavior right-click menu should not show it's instance options

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#374]
When I select an instance under a behavior, and then I right-click the behavior, it shows me the options for the instance, and not for the behavior.

Steps to reproduce:
1. Create a behavior
2. Drop a Standard Element onto the behavior
3. Click on the Instance under the behavior
4. Right-click on the Behavior
5. Notice the context menu is for the instance.
6. Left click on the behavior, back on the instance, back on the behavior
7. Right-click on the behavior that is selected
8. Notice the context menu is still for the instance
9. Left-Click on a component or screen instance
10. Right-click on the behavior
11. Notice the context menu is wrong

Only coming from a Standard Element is the Behavior right-click menu correct.

https://github.com/user-attachments/assets/35e646a2-92bf-44eb-9da9-116b778e77fd

**Comment by kaltinril** [comment]
This also happens when you right-click on folders.

Steps to reproduce:
1. Create a component
2. Drag a Standard Element onto the component
3. Right-click on the Components folder
4. Notice it gives you the context options for the instance, not for the components folder

NOTE: The same thing happens if you right-click on anything after you've selected any instance under any root item.  Component, Screen, or Behavior.  I.E. you can replace the word "component" with screen or behavior in the steps to reproduce.

https://github.com/user-attachments/assets/cac3e786-7307-4f87-ac78-d6c93f1443f5

**Comment by kaltinril** [comment]
This issue comes up all over the place, but the KEY is that you have to select an instance somehow first.

Left-click
Right-click
Drag

All of those will set the selected element in a way that when you left or right click on a non-instance, it will not update the selected element and so context menus are wrong.

**Comment by kaltinril** [comment]
Bumping this to high since it has to many other impacts beyond just behaviors

**Comment by vchelaru** [comment]
I believe this is fixed e153231d5df8f2874951e63f3768c83fcf13fd18

I don't know for sure is because you said it has "other impacts".

**Comment by kaltinril** [comment]
This does appear to be fixed
