### ISSUE TITLE
Suggestion: State Animation menu should not exist

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#375]
Move the View Animation/Hide Animation over under the VIEW menu.

![image](https://github.com/user-attachments/assets/d3a0d506-2d6c-4635-b2e8-8d0e32529ffe)

**Comment by vchelaru** [comment]
![image](https://github.com/user-attachments/assets/66b97f8c-3830-4502-9f26-0d361f42fe55)

a2f40abf280ca5ef38f0752fa512af0aa7218496

**Comment by kaltinril** [comment]
Appears to be working
