### ISSUE TITLE
Suggestion: Hide / Show Tools should be a single menu item

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#376]
Duplicate functionality implemented for Animations and Hotkeys, where the menu item is "Show <Window/Panel>" until it's shown, at which case the menu item changes to "Hide <Window/Panel>"

![image](https://github.com/user-attachments/assets/0c2a08a7-d2dc-47c4-8c79-2257f98663f3)

**Comment by vchelaru** [comment]
Fixed 5f6296dc5e64600320bb3f81c9a8eedad5d6bdd5
