### ISSUE TITLE
Bug: (High) Editor window doesn't reflect the changes to variables when selecting a state (And it should)

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#377]
For some reason the states are not being reflected in the editor.

Steps to reproduce:
1. Create a component
2. Add a Standard Element as an instance of the component
3. Create 1 category
4. Create at least 2 states
5. Click on state1, and move the instance around to change it's variables for that state
6. Click on state2
7. Notice the editor doesn't move the instance position to the correct spot for that state
8. Move the instance while state2 is selected
9. Click back on state 1, notice nothing changes in the editor window
10. click back on state 2, notice nothing changes in the editor window

New functionality (Broken)
https://github.com/user-attachments/assets/2c65ef05-aa68-4dfd-9810-cac96325a548

Old functionality (Working)
https://github.com/user-attachments/assets/eabcb5c0-ed05-4d5f-a7ba-514230160890

**Comment by vchelaru** [comment]
Fixed by 893045ebf69c9785476f9fc596609a55dc97d1a8

**Comment by kaltinril** [comment]
This appears to be fixed
