### ISSUE TITLE
Oddity (Might not be a bug?) State moved to another category, and moved back, retains YELLOW

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#378]
If I move a state from CAT2 to CAT1, and I had previous modified one of the states in CAT1.  Then I move the state back to CAT2, it retains the yellow highlighting, and then everything in cat2 gains the highlighting.

**********2 bugs**************

**Steps to reproduce:**
1. Create a component
2. Add a ColoredRectangle instance
3. Add 2 categories
4. Add 2+ states to Cat1 (state1, state2, etc)
5. Add 2+ states to Cat2 (1state, 2state, etc)
6. Click on state1 in Cat1 and then move it so it sets the state for cat1, and hardcode's the defaults for state2+ in cat1
7.    **BUG1:** notice that the yellow highlighting is missing for all states in cat1
8. Click on something else and back on the instance, notice the yellow highlighting it now present
9. Right-click on "1state" from "Cat2", and chose "Move to Category" > "Cat1"
10. Notice that the yellow highlighting is not present on the "1state" that got moved yet.
11. Right-click on the "1state" that is now in "Cat1" and chose "Move to Category" > "Cat2"
12. **BUG2:** Notice that it suddenly has yellow highlighting on 1state
13. Notice that 2state in cat2 does NOT have highlighting
14. Click somewhere else, and then back on the ColoredRectangleInstance
15. Notice that 1state and 2state in Cat2 now are both yellow.

**Bugs:**
1. Yellow highlighting is not set when a state has modified variables until you click off and then back on
2. Yellow highlighting is propagated now over to cat2, and I do not think I should but I don't know.  perhaps this one is "working as designed"?

https://github.com/user-attachments/assets/8706eb41-6d63-4712-9a4c-ef2712540d32

**Comment by vchelaru** [comment]
Yes these were both bugs. Fixed 0fe886dfb1afb3c80ec81250d526d606aac46e3d
