### ISSUE TITLE
Unable to delete a folder under components

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#381]
I can create and rename folders but Gum will not let me delete folders.

Steps to reproduce:
1. Create a folder in a project
2. Create a sub-folder
3. Right-click on the sub-folder and chose delete folder
4. Click Yes to the popup
5. Get message that you can't delete it

https://github.com/user-attachments/assets/94289c28-d7e7-42ac-b84b-8ebfcdb97211

**Comment by vchelaru** [comment]
I could not reproduce this on my end so maybe it's a permissions thing? Not sure, but I did add more information to the output window when a delete fails. Perhaps you can try it out and see what kind of error is displayed?

Commit with more diagnostics here: bedf69c38d4726848b052d2cc5c65bacffde16d5

**Comment by kaltinril** [comment]
@vchelaru  not much help the output was

![image](https://github.com/user-attachments/assets/c9ddb9c2-2ae6-459d-ba35-b5ca397eae2a)

**Comment by kaltinril** [comment]
![image](https://github.com/user-attachments/assets/aa741169-e789-4b0c-afee-b2bfdfd9bcd1)

![image](https://github.com/user-attachments/assets/ac7f07e5-c582-400f-b717-f3861383aecf)

**Comment by kaltinril** [comment]
I thought it was the double-slashes so I hard coded without them and it still got the error

![image](https://github.com/user-attachments/assets/18f32736-de2a-4383-81a8-a195fa79d51c)

**Comment by kaltinril** [comment]
I'm thinking it's something to do with the way that OneDrive is handling the backups and file access conditions for the directory.

![image](https://github.com/user-attachments/assets/71bde438-3c3c-4c2e-b235-3a4b1f875d4c)

**Comment by kaltinril** [comment]
Yeah, essentially I think that OneDrive is doing some sort of "Archive" setting for the Attributes, which causes Directory.Delete to fail because it "thinks" the file is locked.  However, if you simply tell it to set the attributes to normal first, it works and deletes the file.

I'll submit a bugfix, not sure if you'll want it to not.

![image](https://github.com/user-attachments/assets/b000980c-985c-49ab-86bf-75903c19f9be)

**Comment by kaltinril** [comment]
![Screenshot_20241221_180852_Chrome](https://github.com/user-attachments/assets/895eecf3-cc76-4064-8855-fdc25111b9b7)
