### ISSUE TITLE
When dragging new instances on a screen, cursor is a "prohibited" (🚫) icon

### ISSUE THREAD

**Issue by patridge** [vchelaru/Gum#39]
While following along with the intro tutorial, I added my first item to a screen. While I was dragging around the Text item, the cursor was a prohibited icon which made me think I couldn't place the item anywhere on the screen. When I gave up and released the mouse button, it added just fine, though.

I was kind of expecting some other icon when I was dragging over a valid drop area.

![Screenshot showing the Windows cursor when dragging a Text item onto a screen](https://user-images.githubusercontent.com/713665/64392579-a780d780-d00a-11e9-9dab-2feef7a7d5e3.png)

**Comment by vchelaru** [comment]
![2021_May_11_072513](https://user-images.githubusercontent.com/729631/117821140-7e293d80-b228-11eb-8189-499fae29f074.gif)

Fixed
