### ISSUE TITLE
Gum should allow canceling component import

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#40]
If you start to import components and then change your mind, gum imports them anyway but the tree view may not reflect this.

Repro steps:

1. Have component files somewhere on disk
1. Right-click component folder in Gum and choose "Import"
1. Choose your files on disk (not in the gum project folder)
1. Get notification from Gum with "okay" button only
1. Click the X on the cancel button
1. Components are imported anyway
1. Tree view may not immediately reflect component import

**Comment by vchelaru** [comment]
Fixed!
