### ISSUE TITLE
DOC: Invalid links

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#400]
Here is a quick set, these all point to some logged doc from github?

https://github.com/search?q=repo%3Avchelaru%2FGum%20https%3A%2F%2Fgithub.com%2Fvchelaru%2FGum%2Ftree%2F8c293a405185cca0e819b810220de684b436daf9&type=code

Examples that are on pages on gitbook (See search results above for the hash):

- [ ] 1. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Code%20Reference/RenderingLibrary.IPositionedSizedObject.GetAbsoluteX
- [ ] 2. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Code%20Reference/Gum.DataTypes.ElementSave
- [ ] 3. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Code%20Reference/Gum.DataTypes.StateSave
- [ ] 4. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Code%20Reference/WpfDataUi.DataUiGrid
- [ ] 5. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Code%20Reference/WpfDataUi.DataTypes.InstanceMember.PreferredDisplayer
- [ ] 6. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Code%20Reference/RenderingLibrary.Graphics.Sprite
- [x] 7. https://msxna.codeplex.com/
- [ ] 8. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Code%20Reference/Plugins/README.md
- [ ] 9. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Plugins/Gum%20Class%20Overview/README.md
- [ ] 10. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Plugins/Setting%20Up%20Post%20Build%20Events/README.md
- [ ] 11. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Plugins/PluginBase.AddAndRemoveVariablesForType
- [ ] 12. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Plugins/PluginBase.AddMenuItem
- [ ] 13. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Plugins/PluginBase.Export
- [ ] 14. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/Gum/tutorials/Usage%20Guide%20_%20State%20Categories.html
- [ ] 15. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Elements/General%20Properties/X%20Units/README.md
- [ ] 16. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Elements/General%20Properties/Y%20Units/README.md
- [ ] 17. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Elements/General%20Properties/X%20Origin/README.md
- [ ] 18. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Elements/General%20Properties/Y%20Origin/README.md
- [ ] 19. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Elements/General%20Properties/ColoredRectangle/README.md
- [ ] 20. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/Gum/coloredrectangle/ColoredRectangle.html
- [ ] 21. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Gum%20Elements/General%20Properties/Sprite/README.md
- [ ] 22. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Examples/Width-Units/README.md
- [ ] 23. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Examples/X-Origin/README.md
- [ ] 24. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Examples/X-Units/README.md
- [ ] 25. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Examples/Height-Units/README.md
- [ ] 26. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Examples/Y-Origin/README.md
- [ ] 27. https://github.com/vchelaru/Gum/tree/8c293a405185cca0e819b810220de684b436daf9/docs/Examples/Y-Units/README.md

**Comment by kaltinril** [comment]
Item 7 on the list is not a tree it4em, it is a link on this page
https://docs.flatredball.com/gum/gum-code/gum-code-reference

That tries to go to this page: https://msxna.codeplex.com/

**Comment by kaltinril** [comment]
this is the code i ran to generate the file, change it to .py instead of .txt
[link_verifier.txt](https://github.com/user-attachments/files/18236417/link_verifier.txt)


[crawler_log.csv](https://github.com/user-attachments/files/18236424/crawler_log.csv)

**Comment by kaltinril** [comment]
I've fixed the codeplex one.  

The others I don't know if you actually intend to send people to the github MD files, or if it was a mistake, but if it is on purpose, you should probably use the main (master) branch instead.

If you want the updated link without the commit hash its (.../Gum/blob/master/docs....)

Example: https://github.com/vchelaru/Gum/blob/master/docs/gum-code-reference/renderinglibrary.ipositionedsizedobject.getabsolutex.md

**Comment by kaltinril** [comment]
My gitbook update:  https://app.gitbook.com/o/-M_fyYVTQKWSV65sXTSp/s/-M_fzQmxQ1VeUFHcoo2c/~/changes/316/gum-code/gum-code-reference

**Comment by vchelaru** [comment]
Fixed
