### ISSUE TITLE
BUG: Polygon - Rotation doesn't do anything

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#401]
If rotation is supposed to rotate a polygon, it is broken.

The highlight rectangle when you HOVER over the polygon shows a yellow box that is rotated, but the points do not move.

![image](https://github.com/user-attachments/assets/19de5af3-ec37-4433-b7aa-036a72599da0)

**Comment by vchelaru** [comment]
Fixed by 9db1cb67e7cb0921501d52831d466b26a65d37ba
