### ISSUE TITLE
BUG: Polygon - The highlight rectangle is odd

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#404]
I would expect the highlight rectangle to be around the entire polygon, instead, it seems to be a random box starting at 0,0 and going out approx 32 points?

I created a polygon with 4 more sides (8 total).
When I hover over it, the yellow box appears in the bottom right

![image](https://github.com/user-attachments/assets/57df03ba-0b21-4f76-8a2c-e208096dbc0e)

**Comment by vchelaru** [comment]
![image](https://github.com/user-attachments/assets/0eadf51f-0a95-4151-867d-3290c8952021)
