### ISSUE TITLE
BUG: File Watch path doesn't update when you create a new project (It should)

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#405]
Currently if you create a new project and save it, the File Watch path remains at whatever the previous project was.  This is an issue and should NOT happen.  It SHOULD update to the new Projects path.

Steps to reproduce:
1. Open Gum
2. If a project has not yet been created on this computer, create and save a new project
3. If a project was already open, continue.
4. Click View > Show File Watch
5. Click New Project
6. Notice that the File Watch path remains at whatever the OTHER Project folder path was
7. Click Save project and save it
8. Notice again, file watch path did not update
9. Create some components, instances, etc
10. Notice no changes to file watch path.

https://github.com/user-attachments/assets/802fbee7-0320-426e-afc2-6e805f7e1305

**Comment by vchelaru** [comment]
I believe this is fixed now
