### ISSUE TITLE
Gum is reacting to file changes in unloaded files

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#41]
Gum Output console is reacting to files that it should not know about. I was working in one project and copied that project files into a separate gum project and Gum reacted to the file changes.

Repro:

1. Have a gum project open (Project 1)
1. Have another gum project on disk (Project 2)
1. Manually copy/paste files from Project 1 to Project 2 in the windows file explorer, overwriting files with the same name in Project 2
1. Gum Output console reacts to that change

Screenshot:
![image](https://user-images.githubusercontent.com/711100/98630247-f180df80-22d7-11eb-8680-3602ae81e0bd.png)

**Comment by vchelaru** [comment]
Fixed, Gum is now filters changed files.
