### ISSUE TITLE
Remove Combine States from State/Category panel

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#417]
Research and determine if the combine states has a use or functionality.

If it no longer does, remove it.

If it does, document it and link here so I can test.

![image](https://github.com/user-attachments/assets/ca9365ab-fe99-434f-abc5-4626908a9216)

**Comment by vchelaru** [comment]
Poof! Gone!

![image](https://github.com/user-attachments/assets/2e42dd64-c1ec-48ae-b238-239bde656cf0)
