### ISSUE TITLE
UI: (Low) Behavior deletion should clear the State/Category tab

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#418]
When a behavior is deleted, the State/Category tab/panel should be cleared.  Currently it is not.

Steps to reproduce:
1. Create a behavior
2. Create a category
3. Delete the behavior
4. Notice the category is still displayed

https://github.com/user-attachments/assets/27a101a1-ebb3-48f8-86d1-67ad566ed0ce

**Comment by vchelaru** [comment]
Fixed 8e22cc19438df6d32aa44b2d184054377da5d06d
