### ISSUE TITLE
Gum should see files on disk that are not in the project

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#42]
It's hard to tell if files exist on disk and aren't in Gum. Gum should either:

- Work like Visual Studio in that you can view files that are on disk but not in your project
- Prompt you to add files on disk to your project upon project open
- Have some special window or dialog that shows you files on disk that are not in Gum

**Comment by vchelaru** [comment]
After talking to @profexorgeek , we decided to make this functionality work similar to the way Glue does:

1. If the user selects to import a file, a dialog opens up displaying all local files which can be imported without being copied.
1. If the user selects a file in the dialog, then it is added in its current location
1. The dialog also has a Browse button. If the user clicks the Browse button, a file dialog is displayed
1. If the user selects a local file, it is also added just as if it was selected in the previous dialog
1. If the user selects a file outside of the Gum project, then the user is told that the file will be copied, and is asked if that's okay.

**Comment by vchelaru** [comment]
Fixed!
