### ISSUE TITLE
UX: (Low) Behavior should restrict components for Default Implementation

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#421]
This is low priority

It seem it doesn't make sense that a behavior allows the user to select ANY component.

Instead, perhaps it would be best to limit the selection to components that USE that behavior.

Unless I am not understanding the default implementation functionality.

Explanation:
Imagine you have 2 components from forms, a Button and a Scrollbar.  You go to the ButtonBehavior and select the ScrollBar as the Default Implementation.  That seems odd.

Perhaps it doesn't limit it to the components using that behavior, but they must have the same state/categories?   Unsure.

**Comment by vchelaru** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/672f13e8-b126-4395-8993-6acf08c42722)
