### ISSUE TITLE
Component - Highlight states and categories that belong to the selected behavior

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#422]
When you have multiple behaviors added to a component, you can go to the Behaviors tab on the component, and select a behavior in the list.

This is suggesting that you highlight the specific states/components that are part of that behavior when you click on it in the behavior tab, only when the behavior tab is primary active focused tab/panel.

Mockup (Green highlights) with red line just to indicate the selection.

![image](https://github.com/user-attachments/assets/bc9106d7-c03d-4893-b02d-d0f34ea07a2f)

**Comment by vchelaru** [comment]
I like this, but marking it as enhancement to work on later after bugs are fixed.
