### ISSUE TITLE
UI: (HIGH) Undo removes all behaviors for a component (And it should not)

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#423]
When I was testing behavior I dragged 3 different behaviors onto a component.

- [ ] 1. When I did an undo, the behaviors tab went blank.  I then tried to redo and the behaviors tab was still blank.  This should not happen.
- [ ] 2. The states and categories did not "undo" and remained.  Not sure if this is a bug
- [ ] 3. The REDO did not put the behaviors back.

Steps to reproduce:
1. Create a component
2. Create a behavior "Behave1"
3. Create a behavior "Behave2"
4. Add 1 category and 1 state to Behave1
5. Add 1 category and 1 state to Behave2
6. Drag both behaviors (Behave1 and Behave2) onto the component
7. Perform any other action on the component 
8. Press CTRL+Z to undo the last action
9. Notice the behaviors are missing from the component on the behaviors tab
10. Press CTRL+Y notice the behaviors are not added back
11. Restart gum, notice the behaviors are not there either, they are gone.

https://github.com/user-attachments/assets/5df947b5-e634-4990-8163-41ce921873a3

The Gumx file for the component has no behaviors 

![image](https://github.com/user-attachments/assets/e89e8ee8-34a3-47d5-b67f-30fadd8ca38f)

**Comment by kaltinril** [comment]
Secondary steps, Larger issue:

This even happens if you open an existing project with components and behaviors and then you do a CTRL+Z after doing some un-related behavior chagnes to that component.

Steps to reproduce:
1. Create a new project and save it
2. Create a component
3. Create a behavior with 1 cat and 1 state
4. Close and re-open GUM
5. Re-open the project
6. Add a ColoredRectangle to the component
7. Move the ColoredRectgangle instance on the component
8. Open the Behaviors tab
9. Press CTRL+Z to undo, notice the behaviors are cleared.

**Comment by vchelaru** [comment]
Okay I didn't realize how big of an issue this was until I read the 2nd issue. Ya I agree this is suuuuper high priority and I'm working on a fix now...

**Comment by vchelaru** [comment]
Drag+drop now records undos for behaviors properly.

e7f1c36c1a0962480b926f1877acb3bcd91ff577
