### ISSUE TITLE
UI: (Medium) Application error - Selecting Folder after Behavior Instance

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#424]
When you have an Instance under a Behavior selected, and then you click on the Components Folder, it gives the below error.

Then you you have to close Gum or else the error happens for other things like trying to create a new project

Steps to reproduce:
1. Create a new project and save it
2. Create 1 behavior
3. Drag a single Standard Instance onto the behavior
4. Left-Click on the instance under the behavior
5. Left-Click on any folder (Screens, Components, Standard, Behavior)
6. Error appears
7. Try to create a new project, error appears

![image](https://github.com/user-attachments/assets/54d6bd28-9cbc-4c1d-b06a-290fdebf34ad)

https://github.com/user-attachments/assets/f9b23f86-05ac-49a7-bc35-dcac2dbf984f

**Comment by kaltinril** [comment]
Even simply clicking off of the instance under the behavior causes the error


https://github.com/user-attachments/assets/e5f1e4da-260b-4df4-8eb0-7d1fa85887c4

**Comment by kaltinril** [comment]
This is caused because the SelectedScreen is null, and none of the other events fire.

Inside SelectedState.cs at line 114
1. value and elementBefore are both null, so the first OR condition isn't true
2. next the instancesBefore.count is evaluated and it is larger than 1 so the AND condition can run
3. Now the SelectedScreen is null, so it causes a crash.

This is being set in ElementTreeViewManager.cs line 1476, as it's trying to clear out the selected elements since we selected a folder.

**Resolution:**
I'd simply put a null check in, but I don't know what the purpose of some of these checks is for.   So I don't know if that would be adequate.  

**Suggestion:**
Add a comment above this IF statement, it's unclear the purpose of why you are trying to prevent execution of ElementSelected under these specific conditions.


![image](https://github.com/user-attachments/assets/68076938-5d84-4741-98e4-cd8b499775c5)

**Comment by vchelaru** [comment]
Thanks for researching this. I actually ran into this bug as I was working on a different issue and I fixed this too.
