### ISSUE TITLE
Children of a flipped should not drag-to-move in reversed direction

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#43]
Steps to repro:

- Create a container
- Put a sprite in the container
- Make the container flipped horizontally
- Attempt to drag or rotate the sprite

**Expected behavior:** Sprite drags/rotates normally
**Actual behavior:** X movement and rotation are reversed

![gum-flip-reverse-movement](https://user-images.githubusercontent.com/711100/98865306-6f540080-2428-11eb-843e-293a53bbdbc5.gif)

**Comment by vchelaru** [comment]
Fixed!
