### ISSUE TITLE
Gum should not allow you to drag an item onto itself

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#45]
Repro steps:

- Create a container
- Put items (sprites or whatever) in the container
- Drag the container and drop it onto itself
- Gum clones the container items into the continer

**Expected behavior:** There's no way to cancel an accidental drag. Expectation is that I can cancel a drag by just "putting the item back" where it can from (releasing onto itself).
**Actual behavior:** Gum clones the entire object into itself as a duplicate. Since copy/paste exists there's no reason to have this duplication behavior.

**Comment by vchelaru** [comment]
I cannot repro @profexorgeek see attached gif.
![2020_November_20_085348](https://user-images.githubusercontent.com/729631/99819890-4a891880-2b0d-11eb-8138-f1d1d982365f.gif)

**Comment by profexorgeek** [comment]
I revisited this and also couldn't repro. Maybe got fixed in all of the other recent work?

Go ahead and close. If it happens again I'll try to gif it and open a new issue.
