### ISSUE TITLE
Gum animations should not apply timings to the wrong state

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#47]
There's a bug that I can't specifically repro but it goes something like this:

- Create a gum animation with several states
- Add a named event (maybe do this a couple of times)
- The named event will appear to be selected
- Change the value in the Time input
- Nothing happens
- Click off of the new named event and back onto it
- Change the value in the Time input
- The time value is applied to the named event
- Realize that the first value you entered was applied to some other state

This is a big problem because it messes up your carefully-timed animation but you may not realize it for awhile. Then you have to try to figure out which state got messed up and what it was supposed to be.

**Comment by vchelaru** [comment]
Update, I finally have repro steps:

1. Create a screen
1. Add an object to the screen
1. Select the screen in the tree view
1. Add a few states to the screen
1. Add an animation to the screen
1. Add a few animated keyframes to the animation
1. Click on the animated key frames in the middle column list box. Observe that the properties on the right side update in response to selecting the items in the list box.
1. Click on the object inside the screen in the tree view.
1. Click on different animated keyframes in the list box

Observe: The properties in the right side do not update in response to selecting new keyframes after selecting the new object.
Expected: The right-side should update in response to the list items selected.
