### ISSUE TITLE
Allow dragging screens/components into folders

### ISSUE THREAD

**Issue by bjorn** [vchelaru/Gum#5]
I noticed you can create sub-folders by right-clicking on the Screens or Components tree view entries. Dragging a component or screen into a folder should move it there.

**Comment by vchelaru** [comment]
c40fec80db89f4caf72871bb07c8337edaf8bb22

![2021_May_14_214230](https://user-images.githubusercontent.com/729631/118346847-bb791e00-b4fb-11eb-900f-841da144edc0.gif)
