### ISSUE TITLE
Gum Variables Pane should not be blank

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#62]
It's possible to get Gum into a state where the entire Variables pane is blank. Here are the repro steps:

1. Create a container in either a screen or component (both seem to cause this but a screen definitely does)
2. Put items in the container
3. Select just the container and copy
4. Paste the container into the same screen or component
5. Variables pane goes away

The only way to recover the pane is to close and reopen Gum.

**Comment by profexorgeek** [comment]
This also can happen when deleting items. I'm not sure this repros in every case but I did the following things and the variables pane went blank:

1. Deleted an item
2. Realized I needed to delete a couple more items
3. Shift-clicked two items and deleted
4. Variables pane went away

**Comment by vchelaru** [comment]
Fixed!
