### ISSUE TITLE
Dialog windows should not pop offscreen

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#63]
When adding an animation, the "name animation" dialog pops off the bottom of the screen (covered by taskbar) when Gum is in fullscreen mode. It should be fully visible.

Demo:
![gum-pop-offscreen](https://user-images.githubusercontent.com/711100/102415090-d11e0200-3fb4-11eb-9b92-5354cb082a89.gif)

**Comment by vchelaru** [comment]
Fixed!
