### ISSUE TITLE
Gum movement should not be reversed for flipped components

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#64]
Repro:
1) Create component
2) Add component to a screen
3) Flip component horizontally
4) X movement is reversed when dragging mouse

Gif:
![gum-reverse-move-flipped](https://user-images.githubusercontent.com/711100/103305526-99f21c80-49c8-11eb-8b75-2a15e0b64305.gif)

**Comment by vchelaru** [comment]
Thanks for spotting this. Fixed.
