### ISSUE TITLE
Text preview should be the correct font

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#65]
For some reason Gum is rendering fonts wrong in some cases.

If you don't set a specific state for the text you get a bad preview using some aliased font:
![image](https://user-images.githubusercontent.com/711100/103383521-42c77700-4ab0-11eb-8d7b-c2a8ac32c1db.png)

But if you specify a state (which in this case specifies a font size) you get the correct (non-aliased) font:
![image](https://user-images.githubusercontent.com/711100/103383537-507cfc80-4ab0-11eb-9962-c15798b5c9d3.png)

**Comment by vchelaru** [comment]
As I suspected, this is caused by the Text loading performance improvement. Fixed.
