### ISSUE TITLE
Gum should not collapse parent list when a child item is deleted

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#67]
The tree view refreshes and the parent (such as a container or component) collapses when something is deleted. It shouldn't.

**Comment by vchelaru** [comment]
Fixed. Also, now deleting will select sibling instances and if no siblings exist, then the container instance is selected. This makes multiple deletions easier to do.

![2021_May_10_231204](https://user-images.githubusercontent.com/729631/117761131-10f3b900-b1e4-11eb-8347-da307c2692c6.gif)
