### ISSUE TITLE
Binding actions to an animation shouldn't always throw exceptions?

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#68]
Consider this:
![image](https://user-images.githubusercontent.com/711100/105607485-40c5a080-5d5c-11eb-8c8e-e55449ceaee8.png)

I'm dynamically binding actions to an animation's timed events. In many cases I would want this to explode if the event didn't exist. But in this case different animations support different triggered actions. There should be an optional argument that works something like this:
`AddAction(string actionName, Action triggeredAction, bool suppressErrors = false);`

This way you can have a silent fail option if you know what you're doing and are comfortable with silent failure.

**Comment by vchelaru** [comment]
Added GumAnimation.TryAddAction which returns true if added.
