### ISSUE TITLE
Gum should respect animation setting

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#69]
Gum does not turn achx animation off and on when checking/unchecking the box. As far as I can tell, no code is generated by Glue to turn on/off the animate setting. I tested setting it in code manually and it also did nothing. What I did:

`missile.MissileSprite.Animate = true;`

![gum-no-animate](https://user-images.githubusercontent.com/711100/117543215-14672480-afd9-11eb-813c-3bf973994e0b.gif)

**Comment by vchelaru** [comment]
![2021_May_08_134619](https://user-images.githubusercontent.com/729631/117551004-9ae32c80-b000-11eb-82db-e17dbfe4b1ac.gif)
