### ISSUE TITLE
Gum should duplicate states and animations when duplicating a component

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#73]
Gum has a duplicate feature for components. But when using it, it does not duplicate all of the states and animations from the existing component. Here's the use case:

1. I have a game creature, let's call it a Goomba, with states and animations
2. I want a new MegaGoomba that has the same animations but slightly different positioning and sprites
3. I clone the Goomba, expecting to be able to just tweak the states and be ready to use in game
4. States and animations are not cloned and I must take the time to re-create them

In the case of cloning UI, I may _not_ want all of the states and animations to be cloned. So perhaps Gum should prompt the user with a choice?

If a prompt is not an option, it's definitely faster and easier to _delete_ states and animations you don't want versus _create_ them again!

**Comment by vchelaru** [comment]
Fixed.

c49f247c5ecc1a02972bba709b8513398ad6831b
