### ISSUE TITLE
Gum website: Broken images on project site

### ISSUE THREAD

**Issue by patridge** [vchelaru/Gum#76]
It looks like the screenshots on the project site are returning a 404 error. The images work fine in the Markdown preview, but this rendered static site doesn't seem to work the same.

https://vchelaru.github.io/Gum/

![Screenshot of Gum project website showing no images because they are broken links.](https://user-images.githubusercontent.com/713665/160317048-b740e8a0-d043-41db-b152-e61806210468.png)

For example, the first animation is referencing this relative URL: `.gitbook/assets/Home\_GumGifFast (1).gif`.
In the rendered page, it links to this URL (a 404): `https://vchelaru.github.io/Gum/.gitbook/assets/Home\_GumGifFast (1).gif`

I can't find the appropriate URL to make this link work in the rendered page.

Source: https://github.com/vchelaru/Gum/blame/master/docs/README.md#L21-L29

Here are the relative image links that are not working.

```html
![](<.gitbook/assets/Home\_GumGifFast (1).gif>)

![](<.gitbook/assets/Home\_GumPromo1 (1).PNG>)

![](<.gitbook/assets/Home\_GumPromo2 (1).PNG>)

![](<.gitbook/assets/Home\_GumPromo3 (1).PNG>)

![](<.gitbook/assets/Home\_GumPromo4 (1).PNG>)
```

**Comment by vchelaru** [comment]
How did you find a link to this page? The proper documentation site is:

https://flatredball.gitbook.io/gum/

If anything links to that old page it needs to be killed.

**Comment by vchelaru** [comment]
I unlisted that page through Github.
