### ISSUE TITLE
Error when cancelling drag-and-drop from Standard items

### ISSUE THREAD

**Issue by patridge** [vchelaru/Gum#77]
This might be confusion or lack of a better alternative to aborting a drag-and-drop operation, but the error message had me worried to cancel drag-and-drop operations that start in other sections.

## Steps

1. Start dragging an element from the **Standard** items (e.g., `ColoredRectangle`)
2. Drag over to **Editor** panel (or up to a **Screens** entry), and then back to **Standard** tree items
3. Release item

Results in this error pop-up:

![Screenshot of alert in Gum saying "Standard types can't contain objects".](https://user-images.githubusercontent.com/713665/161117591-6861c5fc-c7d2-4158-9c68-46b5dedbec60.png)

Recording:

![Recording of drag and drop operation cancelled and getting the above alert.](https://user-images.githubusercontent.com/713665/161118224-45db88c6-7f1c-4d48-a88f-b19e5378926a.gif)

**Comment by vchelaru** [comment]
@patridge in this case, the fact that you drag over the editor panel doesn't actually matter. Ultimately you are dragging a ColoredRectangle onto a Circle, and the Circle standard type cannot contain any instances so this is not allowed. 

The error message could be a little more informative, so I've adjusted it:

![image](https://user-images.githubusercontent.com/729631/175656356-f7590e3d-0423-4beb-b554-4d447db77888.png)

If you have ideas on better wording let me know.

The updated text is fixed:

738a439a410ed90db774bf488b57ea15393b99db
